// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM0a4FzoTpJtzsNIHBCImYiq9mVTDNZMU',
    appId: '1:565156667961:web:c587a2f3e23d985caee3e8',
    messagingSenderId: '565156667961',
    projectId: 'e-com-55acd',
    authDomain: 'e-com-55acd.firebaseapp.com',
    storageBucket: 'e-com-55acd.firebasestorage.app',
    measurementId: 'G-0RDR0LHT9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu1nTdECj3qbNzmap5K-yjkS85mNoV1Yo',
    appId: '1:565156667961:android:4f23900240e1588baee3e8',
    messagingSenderId: '565156667961',
    projectId: 'e-com-55acd',
    storageBucket: 'e-com-55acd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfc8f1p80gflEtlTFx5JPFuydAIxmkXnc',
    appId: '1:565156667961:ios:aa0839751f6b4712aee3e8',
    messagingSenderId: '565156667961',
    projectId: 'e-com-55acd',
    storageBucket: 'e-com-55acd.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );
}
